/**
 * The journey line (viewer dashboard V5). Founder-approved copy verbatim
 * (2026-07-21):
 *   Y > 0: "This film has reached [X] people. [Y] of them received it
 *           because of you."
 *   Y = 0: "This film has reached [X] people. Grow that number by sharing
 *           the film." (revised 2026-07-22)
 *
 * ONE shared computation per the canonical-stats rule. Numbers render as
 * NUMERALS ("4", "58") — never spelled out.
 *
 * THE COUNTS COME FROM THE CONSTELLATION'S TREE (owner rule 2026-07-21 —
 * a single counting path, buildConstellationLayout):
 *   X (`reached`)    = every ticket generated across the film, ghosts
 *                      excluded (layout.inviteCount)
 *   Y (`downstream`) = the viewer's ENTIRE downstream — links they
 *                      generated plus links generated by anyone beneath
 *                      them in the tree, all depths
 *                      (layout.viewerDownstreamCount)
 *
 * DOCUMENTED DEVIATION from the canonical "reach" stat (src/lib/reach.js,
 * decided 2026-07-16): reach counts OPENED invites; this line deliberately
 * counts GENERATED links (owner decision 2026-07-20) so the line, the
 * ticket rows, and the constellation all describe the same set of tickets.
 * Do not "fix" one to match the other.
 */
const people = (n) => `${n} ${n === 1 ? 'person' : 'people'}`

/** @returns segments [{ text, bold }] — render bold segments in gold */
export function buildJourneyLine({ reached = 0, downstream = 0 } = {}) {
  if (downstream > 0) {
    return {
      reached,
      downstream,
      segments: [
        { text: 'This film has reached ', bold: false },
        { text: people(reached), bold: true },
        { text: '. ', bold: false },
        { text: `${downstream} of them`, bold: true },
        { text: ' received it because of you.', bold: false },
      ],
    }
  }
  return {
    reached,
    downstream,
    segments: [
      { text: 'This film has reached ', bold: false },
      { text: people(reached), bold: true },
      { text: '. Grow that number by sharing the film.', bold: false },
    ],
  }
}
