/**
 * Creator admin table — one row per PERSON in a film's network (2026-07-17).
 *
 * A person is the union of:
 * - every invite recipient identifiable by email (legacy rows keep the address
 *   in recipient_email; claim-link rows carry it in claimed_email once
 *   claimed), merged across all their invites for the film, and
 * - every non-creator sender with a users row (team members appear here even
 *   when no invite is addressed to them).
 *
 * A generated-but-unclaimed link invite has a first name and no email — it is
 * NOT a person row yet; it is visible inside its sharer's "generated" count.
 * The film's creator never gets a row (they are the graph root, not a member
 * of their own audience).
 *
 * Counting rule (structural, not incidental): an account holder's sends carry
 * their sender_id, but a link generated by an ACCOUNTLESS claimant has
 * sender_id NULL — the child's parent_invite_id pointing at the claimant's own
 * claimed invite is the only back-link. "Tickets generated" is therefore the
 * union of both matches, counted once per invite row.
 *
 * Reach is the canonical stat from src/lib/reach.js, unchanged: claimed-but-
 * unwatched people do NOT count toward reach (decision 2026-07-16), even
 * though they DO count in this table's "claimed" column.
 */
import { buildChildrenByParentId, computeUserReach } from './reach.js'
import { isInviteClaimedStage } from './ticketFunnel.js'
import { isInviteWatched } from './filmStats.js'

const normEmail = (e) => (typeof e === 'string' ? e.trim().toLowerCase() : '')

/** The email that identifies an invite's recipient: the claim wins, else the
 *  legacy address. Empty string when the ticket is still unclaimed. */
export function inviteRecipientEmail(inv) {
  return normEmail(inv?.claimed_email) || normEmail(inv?.recipient_email)
}

/** Highest stage a person's own received invites reached. */
function personStage({ hasAccount, receivedStatuses }) {
  if (hasAccount || receivedStatuses.includes('signed_up')) return 'signed_up'
  if (receivedStatuses.some((s) => isInviteWatched({ status: s }))) return 'watched'
  if (receivedStatuses.some((s) => isInviteClaimedStage({ status: s }))) return 'claimed'
  return 'invited'
}

/**
 * Build the person rows for one film.
 *
 * @param filmInvites all invite rows for the film (any status)
 * @param users       the users rows already loaded for the film's senders
 *                    ({ id, name, email }) — used to resolve names/accounts
 * @param creatorId   the film's creator (excluded from the rows)
 */
export function buildNetworkPeople({ filmInvites, users, creatorId } = {}) {
  const invites = filmInvites || []
  const childrenByParentId = buildChildrenByParentId(invites)
  const creatorKey = creatorId ? String(creatorId) : null

  const userById = new Map()
  const userByEmail = new Map()
  for (const u of users || []) {
    if (u?.id != null) userById.set(String(u.id), u)
    const e = normEmail(u?.email)
    if (e) userByEmail.set(e, u)
  }

  const people = new Map()
  const ensurePerson = (email) => {
    if (!people.has(email)) {
      people.set(email, {
        email,
        inviteName: '',
        userId: null,
        userName: '',
        receivedInviteIds: new Set(),
        receivedStatuses: [],
        firstReceivedAt: null,
      })
    }
    return people.get(email)
  }

  // 1) Recipients and claimants — one accumulator per email.
  for (const inv of invites) {
    const email = inviteRecipientEmail(inv)
    if (!email) continue // unclaimed link — a ticket, not a person yet
    const p = ensurePerson(email)
    if (inv.id != null) p.receivedInviteIds.add(inv.id)
    p.receivedStatuses.push(inv.status)
    if (!p.inviteName && inv.recipient_name) p.inviteName = inv.recipient_name
    const at = inv.created_at || null
    if (at && (!p.firstReceivedAt || at < p.firstReceivedAt)) p.firstReceivedAt = at
  }

  // 2) Non-creator senders — covers team members who never received an invite.
  for (const inv of invites) {
    const senderId = inv?.sender_id != null ? String(inv.sender_id) : ''
    if (!senderId || senderId === creatorKey) continue
    const u = userById.get(senderId)
    const email = normEmail(u?.email) || normEmail(inv.sender_email)
    if (!email) continue
    const p = ensurePerson(email)
    p.userId = p.userId || senderId
    if (u?.name) p.userName = u.name
    else if (!p.userName && inv.sender_name) p.userName = inv.sender_name
  }

  // 3) Resolve accounts by email for people who only received.
  for (const p of people.values()) {
    const u = userByEmail.get(p.email)
    if (u) {
      p.userId = p.userId || String(u.id)
      if (u.name) p.userName = u.name
    }
  }

  // The creator is the root, never a row.
  if (creatorKey) {
    for (const [email, p] of people) {
      if (p.userId === creatorKey) people.delete(email)
    }
  }

  const rows = []
  for (const p of people.values()) {
    // Union of both back-links, counted once per invite row.
    const generated = invites.filter(
      (inv) =>
        (p.userId && String(inv.sender_id ?? '') === p.userId) ||
        (inv.parent_invite_id != null && p.receivedInviteIds.has(inv.parent_invite_id))
    )
    const hasAccount = Boolean(p.userId) || p.receivedStatuses.includes('signed_up')
    rows.push({
      email: p.email,
      name: p.userName || p.inviteName || p.email.split('@')[0],
      hasAccount,
      stage: personStage({ hasAccount, receivedStatuses: p.receivedStatuses }),
      ticketsGenerated: generated.length,
      ticketsClaimed: generated.filter(isInviteClaimedStage).length,
      reach: computeUserReach(generated, childrenByParentId),
      receivedInviteIds: [...p.receivedInviteIds],
      firstReceivedAt: p.firstReceivedAt,
    })
  }

  // Chain order (first invite received); senders with no received invite
  // (team members) sort after, by name.
  rows.sort((a, b) => {
    if (a.firstReceivedAt && b.firstReceivedAt) {
      return a.firstReceivedAt < b.firstReceivedAt ? -1 : a.firstReceivedAt > b.firstReceivedAt ? 1 : 0
    }
    if (a.firstReceivedAt) return -1
    if (b.firstReceivedAt) return 1
    return a.name.localeCompare(b.name)
  })
  return rows
}
