/**
 * Creator admin table — one row per PERSON in a film's network, plus one row
 * per outstanding ticket (2026-07-17, three-status display since A2).
 *
 * A person is the union of:
 * - every invite recipient identifiable by email (legacy rows keep the address
 *   in recipient_email; claim-link rows carry it in claimed_email once
 *   claimed), merged across all their invites for the film, and
 * - every non-creator sender with a users row (team members appear here even
 *   when no invite is addressed to them).
 *
 * A generated-but-unclaimed link (status 'created', no email yet) is an
 * outstanding TICKET row (kind 'ticket', keyed by invite id since no email
 * exists): first name, the claim link's slug for recovery, and nothing else.
 * Ticket rows sort to the top, newest first, so outstanding links are
 * immediately visible; person rows keep chain order below.
 * The film's creator never gets a row (they are the graph root, not a member
 * of their own audience).
 *
 * Status is exactly three values (display mapping only, founder-approved A2):
 * 'unclaimed' (created / legacy pending), 'claimed' (claimed / legacy opened),
 * 'watched' (watched / legacy signed_up — account holders count as watched).
 *
 * Counting rule (structural, not incidental): an account holder's sends carry
 * their sender_id, but a link generated by an ACCOUNTLESS claimant has
 * sender_id NULL — the child's parent_invite_id pointing at the claimant's own
 * claimed invite is the only back-link. "Tickets generated" is therefore the
 * union of both matches, counted once per invite row.
 *
 * Tickets left: an accountless claimant's balance lives on their own claimed
 * invite row (tickets_remaining; NULL means claimed pre-migration and reads as
 * the full grant — same healing rule as the server spend). Account holders'
 * allocation is NOT part of the film's invite rows, so claimTicketsLeft is
 * null for them and the display layer decides (∞ for unlimited, em dash when
 * the allocation isn't loaded).
 *
 * Reach is the canonical stat from src/lib/reach.js, unchanged: claimed-but-
 * unwatched people do NOT count toward reach (decision 2026-07-16), even
 * though they DO count in this table's "claimed" column.
 */
import { buildChildrenByParentId, computeUserReach } from './reach.js'
import { isInviteClaimedStage } from './ticketFunnel.js'
import { isInviteWatched } from './filmStats.js'
import { INITIAL_CLAIMANT_TICKETS } from './ticketRules.js'

const normEmail = (e) => (typeof e === 'string' ? e.trim().toLowerCase() : '')

/** The email that identifies an invite's recipient: the claim wins, else the
 *  legacy address. Empty string when the ticket is still unclaimed. */
export function inviteRecipientEmail(inv) {
  return normEmail(inv?.claimed_email) || normEmail(inv?.recipient_email)
}

/** Highest of the three display stages a person's own invites reached. */
function personStage({ hasAccount, receivedStatuses }) {
  if (hasAccount || receivedStatuses.some((s) => isInviteWatched({ status: s }))) return 'watched'
  if (receivedStatuses.some((s) => isInviteClaimedStage({ status: s }))) return 'claimed'
  return 'unclaimed'
}

/**
 * Build the rows for one film: outstanding-ticket rows first (newest first),
 * then person rows in chain order.
 *
 * @param filmInvites all invite rows for the film (any status)
 * @param users       the users rows already loaded for the film's senders
 *                    ({ id, name, email }) — used to resolve names/accounts
 * @param creatorId   the film's creator (excluded from the rows)
 */
export function buildNetworkPeople({ filmInvites, users, creatorId } = {}) {
  const invites = filmInvites || []
  const childrenByParentId = buildChildrenByParentId(invites)
  const creatorKey = creatorId ? String(creatorId) : null

  const userById = new Map()
  const userByEmail = new Map()
  for (const u of users || []) {
    if (u?.id != null) userById.set(String(u.id), u)
    const e = normEmail(u?.email)
    if (e) userByEmail.set(e, u)
  }

  const people = new Map()
  const ensurePerson = (email) => {
    if (!people.has(email)) {
      people.set(email, {
        email,
        inviteName: '',
        userId: null,
        userName: '',
        receivedInviteIds: new Set(),
        receivedStatuses: [],
        claimTickets: undefined, // tickets_remaining on their claimed row
        hasClaimRow: false,
        firstReceivedAt: null,
      })
    }
    return people.get(email)
  }

  // 0) Outstanding tickets — generated links nobody has claimed yet.
  const ticketRows = []
  for (const inv of invites) {
    if (inv?.status === 'created' && !inviteRecipientEmail(inv)) {
      ticketRows.push({
        kind: 'ticket',
        id: inv.id,
        name: inv.recipient_name || 'invite',
        slug: inv.link_slug || null,
        createdAt: inv.created_at || null,
      })
    }
  }
  ticketRows.sort((a, b) =>
    (b.createdAt || '') < (a.createdAt || '') ? -1 : (b.createdAt || '') > (a.createdAt || '') ? 1 : 0
  )

  // 1) Recipients and claimants — one accumulator per email.
  for (const inv of invites) {
    const email = inviteRecipientEmail(inv)
    if (!email) continue // outstanding ticket — handled above
    const p = ensurePerson(email)
    if (inv.id != null) p.receivedInviteIds.add(inv.id)
    p.receivedStatuses.push(inv.status)
    if (!p.inviteName && inv.recipient_name) p.inviteName = inv.recipient_name
    if (normEmail(inv.claimed_email)) {
      p.hasClaimRow = true
      if (p.claimTickets === undefined) p.claimTickets = inv.tickets_remaining ?? null
    }
    const at = inv.created_at || null
    if (at && (!p.firstReceivedAt || at < p.firstReceivedAt)) p.firstReceivedAt = at
  }

  // 2) Non-creator senders — covers team members who never received an invite.
  for (const inv of invites) {
    const senderId = inv?.sender_id != null ? String(inv.sender_id) : ''
    if (!senderId || senderId === creatorKey) continue
    const u = userById.get(senderId)
    const email = normEmail(u?.email) || normEmail(inv.sender_email)
    if (!email) continue
    const p = ensurePerson(email)
    p.userId = p.userId || senderId
    if (u?.name) p.userName = u.name
    else if (!p.userName && inv.sender_name) p.userName = inv.sender_name
  }

  // 3) Resolve accounts by email for people who only received.
  for (const p of people.values()) {
    const u = userByEmail.get(p.email)
    if (u) {
      p.userId = p.userId || String(u.id)
      if (u.name) p.userName = u.name
    }
  }

  // The creator is the root, never a row.
  if (creatorKey) {
    for (const [email, p] of people) {
      if (p.userId === creatorKey) people.delete(email)
    }
  }

  const personRows = []
  for (const p of people.values()) {
    // Union of both back-links, counted once per invite row.
    const generated = invites.filter(
      (inv) =>
        (p.userId && String(inv.sender_id ?? '') === p.userId) ||
        (inv.parent_invite_id != null && p.receivedInviteIds.has(inv.parent_invite_id))
    )
    const hasAccount = Boolean(p.userId) || p.receivedStatuses.includes('signed_up')
    personRows.push({
      kind: 'person',
      email: p.email,
      name: p.userName || p.inviteName || p.email.split('@')[0],
      hasAccount,
      stage: personStage({ hasAccount, receivedStatuses: p.receivedStatuses }),
      ticketsGenerated: generated.length,
      ticketsClaimed: generated.filter(isInviteClaimedStage).length,
      // NULL on a claimed row means claimed pre-migration → full grant (the
      // server heals it on first spend). Account holders get null: their
      // allocation lives on users, not on the film's invite rows.
      claimTicketsLeft:
        !hasAccount && p.hasClaimRow ? (p.claimTickets ?? INITIAL_CLAIMANT_TICKETS) : null,
      reach: computeUserReach(generated, childrenByParentId),
      receivedInviteIds: [...p.receivedInviteIds],
      firstReceivedAt: p.firstReceivedAt,
    })
  }

  // Chain order (first invite received); senders with no received invite
  // (team members) sort after, by name.
  personRows.sort((a, b) => {
    if (a.firstReceivedAt && b.firstReceivedAt) {
      return a.firstReceivedAt < b.firstReceivedAt ? -1 : a.firstReceivedAt > b.firstReceivedAt ? 1 : 0
    }
    if (a.firstReceivedAt) return -1
    if (b.firstReceivedAt) return 1
    return a.name.localeCompare(b.name)
  })

  return [...ticketRows, ...personRows]
}
